language: python
python:
  - "3.6"
install:
  - pip3 install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database questioner_test;' -U postgres

script:
  - pytest --cov=app

after_success:
  - coveralls